FROM nginx:stable-alpine AS base

RUN printf "\
    server {\n\
        listen 80;\n\
        error_log /var/log/nginx/error.log;\n\
        access_log /var/log/nginx/access.log;\n\
        location /api/ {\n\
            proxy_pass http://node:5000/;\n\
            proxy_set_header Host \$host;\n\
            proxy_set_header X-Real-IP \$remote_addr;\n\
            proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;\n\
            proxy_set_header X-Forwarded-Proto \$scheme;\n\
        }\n\
    }\n" > /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]