FROM nginx:stable-alpine AS base

RUN printf "\
    server {\n\
        listen 80;\n\
        error_log /var/log/nginx/error.log;\n\
        access_log /var/log/nginx/access.log;\n\
        location /api/ {\n\
            proxy_pass http://node:5000/;\n\
            proxy_set_header Host \$host;\n\
            proxy_set_header X-Real-IP \$remote_addr;\n\
            proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;\n\
            proxy_set_header X-Forwarded-Proto \$scheme;\n\
            add_header 'Access-Control-Allow-Origin' 'http://173.212.236.33:24010' always;\n\
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;\n\
            add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization' always;\n\
            add_header 'Access-Control-Allow-Credentials' 'true' always;\n\
            if ($request_method = 'OPTIONS') {\n\
            add_header 'Access-Control-Allow-Origin' 'http://173.212.236.33:24010';\n\
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS';\n\
            add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization';\n\
            add_header 'Content-Type' 'text/plain charset=UTF-8';\n\
            add_header 'Access-Control-Max-Age' 1728000;\n\
            add_header 'Content-Length' 0;\n\
            return 204;\n\
            }\n\
        }\n\
    }\n" > /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]